### ISSUE TITLE
Issues with existing Laravel installation

### ISSUE THREAD

**Issue by aglipanci** [laravel/octane#252]
- Octane Version: 0.4
- Laravel Version: 8.40
- PHP Version: 8.0.1
- Server: RoadRunner
- Database Driver & Version: MySQL 8.0.23

### Description:
I have an existing Laravel app that I have upgraded to the latest version, when I run it with Octane the login form returns a 419 expired error, something that doesn't happen when I run it on Homestead.  Even if I try to remove the VerifyCsrfToken middleware the authentication won't happen. This issue happens with any other form as well.

Based on the error logs (I have included here) it seems like there are some issues with the request and it's not being handled properly by roadrunner or it's being modified along the way on Laravel. 

The same behaviour when running with swoole.

### Steps To Reproduce:
It's really hard to reproduce because if you try a fresh install, even with my dependencies it will work fine. For authentication, I am using laravel/ui package and I haven't modified anything from the standard install.

Composer dependencies:
```
"require": {
        "fideloper/proxy": "^4.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "intervention/image": "^2.4",
        "kyslik/column-sortable": "^6.0",
        "laracasts/utilities": "^3.0.1",
        "laravel/framework": "^8.0",
        "laravel/legacy-factories": "^1.1",
        "laravel/nova": "~3.0",
        "laravel/octane": "^0.4.0",
        "laravel/ui": "^3.0",
        "sentry/sentry-laravel": "^2.4.1",
        "spiral/roadrunner": "^2.0",
        "tightenco/ziggy": "^1.0"
    },
    "require-dev": {
        "barryvdh/laravel-ide-helper": "^2.9",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.0"
    },
```

Middlewares:

```
    protected $middleware = [
        \App\Http\Middleware\CheckForMaintenanceMode::class,
        \Illuminate\Foundation\Http\Middleware\ValidatePostSize::class,
        \App\Http\Middleware\TrimStrings::class,
        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
        \App\Http\Middleware\TrustProxies::class,
    ];

    protected $middlewareGroups = [
        'web' => [
            \App\Http\Middleware\EncryptCookies::class,
            \Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
            \Illuminate\Session\Middleware\StartSession::class,
            // \Illuminate\Session\Middleware\AuthenticateSession::class,
            \Illuminate\View\Middleware\ShareErrorsFromSession::class,
            \App\Http\Middleware\VerifyCsrfToken::class,
            \Illuminate\Routing\Middleware\SubstituteBindings::class,
        ],

        'api' => [
            'throttle:60,1',
            'bindings',
        ],
    ];
```

Roadrunner error logs:

```
[2021-04-29 08:03:40] local.ERROR: unable to read frame header {"exception":"[object] (Spiral\\Goridge\\Exception\\HeaderException(code: 0): unable to read frame header at /home/vagrant/code/app/vendor/spiral/goridge/src/StreamRelay.php:71)
[stacktrace]
#0 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Worker.php(83): Spiral\\Goridge\\StreamRelay->waitFrame()
#1 /home/vagrant/code/app/vendor/spiral/roadrunner-http/src/HttpWorker.php(67): Spiral\\RoadRunner\\Worker->waitPayload()
#2 /home/vagrant/code/app/vendor/spiral/roadrunner-http/src/PSR7Worker.php(93): Spiral\\RoadRunner\\Http\\HttpWorker->waitRequest()
#3 /home/vagrant/code/app/vendor/laravel/octane/bin/roadrunner-worker(40): Spiral\\RoadRunner\\Http\\PSR7Worker->waitRequest()
#4 {main}
"} 
[2021-04-29 08:03:40] local.ERROR: unable to read frame header {"exception":"[object] (Spiral\\Goridge\\Exception\\HeaderException(code: 0): unable to read frame header at /home/vagrant/code/app/vendor/spiral/goridge/src/StreamRelay.php:71)
[stacktrace]
#0 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Worker.php(83): Spiral\\Goridge\\StreamRelay->waitFrame()
#1 /home/vagrant/code/app/vendor/spiral/roadrunner-http/src/HttpWorker.php(67): Spiral\\RoadRunner\\Worker->waitPayload()
#2 /home/vagrant/code/app/vendor/spiral/roadrunner-http/src/PSR7Worker.php(93): Spiral\\RoadRunner\\Http\\HttpWorker->waitRequest()
#3 /home/vagrant/code/app/vendor/laravel/octane/bin/roadrunner-worker(40): Spiral\\RoadRunner\\Http\\PSR7Worker->waitRequest()
#4 {main}
"} 
[2021-04-29 08:03:40] local.ERROR: Uncaught ErrorException: file_put_contents(): Write of 153300 bytes failed with errno=32 Broken pipe in /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php:38
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php(38): file_put_contents()
#2 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php(30): Spiral\RoadRunner\Logger->write()
#3 /home/vagrant/code/app/vendor/psr/log/Psr/Log/LoggerTrait.php(127): Spiral\RoadRunner\Logger->log()
#4 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Internal/StdoutHandler.php(82): Spiral\RoadRunner\Logger->debug()
#5 /home/vagrant/code/app/vendor/symfony/http-foundation/Response.php(381): Spiral\RoadRunner\Internal\StdoutHandler::Spiral\RoadRunner\Internal\{closure}()
#6 /home/vagrant/code/app/vendor/symfony/http-foundation/Response.php(394): Symfony\Component\HttpFoundation\Response->sendContent()
#7 /home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Symfony\Component\HttpFoundation\Response->send()
#8 /home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse()
#9 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#10 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ErrorException: file_put_contents(): Write of 153300 bytes failed with errno=32 Broken pipe in /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php:38
Stack trace:
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php(38): file_put_contents()
#2 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php(30): Spiral\\RoadRunner\\Logger->write()
#3 /home/vagrant/code/app/vendor/psr/log/Psr/Log/LoggerTrait.php(127): Spiral\\RoadRunner\\Logger->log()
#4 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Internal/StdoutHandler.php(82): Spiral\\RoadRunner\\Logger->debug()
#5 /home/vagrant/code/app/vendor/symfony/http-foundation/Response.php(381): Spiral\\RoadRunner\\Internal\\StdoutHandler::Spiral\\RoadRunner\\Internal\\{closure}()
#6 /home/vagrant/code/app/vendor/symfony/http-foundation/Response.php(394): Symfony\\Component\\HttpFoundation\\Response->sendContent()
#7 /home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Symfony\\Component\\HttpFoundation\\Response->send()
#8 /home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()
#9 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#10 {main}
  thrown at /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php:38)
[stacktrace]
#0 {main}
"} 
[2021-04-29 08:03:40] local.ERROR: Uncaught ErrorException: file_put_contents(): Write of 151777 bytes failed with errno=32 Broken pipe in /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php:38
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php(38): file_put_contents()
#2 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php(30): Spiral\RoadRunner\Logger->write()
#3 /home/vagrant/code/app/vendor/psr/log/Psr/Log/LoggerTrait.php(127): Spiral\RoadRunner\Logger->log()
#4 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Internal/StdoutHandler.php(82): Spiral\RoadRunner\Logger->debug()
#5 /home/vagrant/code/app/vendor/symfony/http-foundation/Response.php(381): Spiral\RoadRunner\Internal\StdoutHandler::Spiral\RoadRunner\Internal\{closure}()
#6 /home/vagrant/code/app/vendor/symfony/http-foundation/Response.php(394): Symfony\Component\HttpFoundation\Response->sendContent()
#7 /home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Symfony\Component\HttpFoundation\Response->send()
#8 /home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse()
#9 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#10 {main}
  thrown {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Uncaught ErrorException: file_put_contents(): Write of 151777 bytes failed with errno=32 Broken pipe in /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php:38
Stack trace:
#0 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php(38): file_put_contents()
#2 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php(30): Spiral\\RoadRunner\\Logger->write()
#3 /home/vagrant/code/app/vendor/psr/log/Psr/Log/LoggerTrait.php(127): Spiral\\RoadRunner\\Logger->log()
#4 /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Internal/StdoutHandler.php(82): Spiral\\RoadRunner\\Logger->debug()
#5 /home/vagrant/code/app/vendor/symfony/http-foundation/Response.php(381): Spiral\\RoadRunner\\Internal\\StdoutHandler::Spiral\\RoadRunner\\Internal\\{closure}()
#6 /home/vagrant/code/app/vendor/symfony/http-foundation/Response.php(394): Symfony\\Component\\HttpFoundation\\Response->sendContent()
#7 /home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(119): Symfony\\Component\\HttpFoundation\\Response->send()
#8 /home/vagrant/code/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(96): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()
#9 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()
#10 {main}
  thrown at /home/vagrant/code/app/vendor/spiral/roadrunner-worker/src/Logger.php:38)
[stacktrace]
#0 {main}
"} 
```

**Comment by nunomaduro** [comment]
@aglipanci I am sorry - please try to create a GitHub repository with clear instructions ( including drivers used ) on how to reproduce this error. If you can't make this happen, please try to get help in one of the following channels:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

However, this issue will not be locked and everyone is still free to discuss solutions to your problem!

Thanks.

**Comment by aglipanci** [comment]
I had SESSION_DOMAIN configured on my .env file. That was the issue :/

**Comment by mubahood** [comment]
You must be having an error in your code, check in the terminal when you launch the site. You will see an issue written in terminal, so the server crashes and stop working hence loading forever. 
What to do, see when your project begins, them test line by line and you will see the culprit.
