### ISSUE TITLE
Undefined array key "type" in InteractsWithIO

### ISSUE THREAD

**Issue by foremtehan** [laravel/octane#417]
- Octane Version: 1.0.16
- Laravel Version: 8,68
- PHP Version: 8
- Server & Version: Swoole

### Description:
I dump some php super global variables and octane come with the following error:

```
Undefined array key "type"#0 /app/vendor/laravel/octane/src/Commands/Concerns/InteractsWithIO.php(229): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /app/vendor/laravel/octane/src/Commands/StartSwooleCommand.php(177): Laravel\Octane\Commands\Command->handleStream()
#2 /app/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Laravel\Octane\Commands\StartSwooleCommand->Laravel\Octane\Commands\{closure}()
#3 /app/vendor/laravel/octane/src/Commands/StartSwooleCommand.php(179): Illuminate\Support\Collection->each()
#4 /app/vendor/laravel/octane/src/Commands/Concerns/InteractsWithServers.php(32): Laravel\Octane\Commands\StartSwooleCommand->writeServerOutput()
#5 /app/vendor/laravel/octane/src/Commands/StartSwooleCommand.php(87): Laravel\Octane\Commands\StartSwooleCommand->runServer()
#6 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Octane\Commands\StartSwooleCommand->handle()
#7 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#8 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#9 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#10 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#11 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#12 /app/vendor/symfony/console/Command/Command.php(299): Illuminate\Console\Command->execute()
#13 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#14 /app/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(68): Illuminate\Console\Command->run()
#15 /app/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\Console\Command->runCommand()
#16 /app/vendor/laravel/octane/src/Commands/StartCommand.php(63): Illuminate\Console\Command->call()
```

### Steps To Reproduce:

```php
Route::get('/test', function (){
    dump($_SERVER);
    dump($_REQUEST);
    dump(getallheaders());
});
```

(it also print the data inside of the console rather than then browser)

**Comment by foremtehan** [comment]
https://github.com/laravel/octane/pull/413
