### ISSUE TITLE
Swoole\Table::set(): failed to set('cache.key'), unable to allocate memory

### ISSUE THREAD

**Issue by foremtehan** [laravel/octane#440]
- Octane Version: 1.0.21
- Laravel Version: 8
- PHP Version: 8
- Server & Version: Swoole 

### Description:
I saw this error in my logs just want to let you know about it, Because it doesnt happen for all keys

### Steps To Reproduce:

```php
Cache::store('octane)->put('cache.key', 1, now()->addMinutes(3));
```

```
Swoole\Table::set(): failed to set('cache.key'), unable to allocate memory#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /app/vendor/laravel/octane/src/Cache/OctaneStore.php(84): Swoole\Table->set()
#2 /app/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(213): Laravel\Octane\Cache\OctaneStore->put()
#3 [internal function]: Illuminate\Routing\RouteFileRegistrar->{closure}()
#4 /app/vendor/laravel/octane/src/Concerns/ProvidesRouting.php(53): call_user_func()
#5 /app/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(261): Laravel\Octane\Octane->invokeRoute()
#6 /app/vendor/laravel/octane/src/ApplicationGateway.php(33): Illuminate\Support\Facades\Facade::__callStatic()
#9 /app/vendor/laravel/octane/src/Worker.php(92): Laravel\Octane\ApplicationGateway->handle()
#10 /app/vendor/laravel/octane/bin/swoole-server(117): Laravel\Octane\Worker->handle()
#11 [internal function]: {closure}()
#12 /app/vendor/laravel/octane/bin/swoole-server(163): Swoole\Server->start()
#13 {main}
```

**Comment by driesvints** [comment]
That seems like a hiccup on your own device. Please try a support channel:

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)
