### ISSUE TITLE
OpenSwoole v22.0.0

### ISSUE THREAD

**Issue by tobiasdalhof** [laravel/octane#625]
Laravel Octane and OpenSwoole [v22.0.0](https://github.com/openswoole/swoole-src/releases/tag/v22.0.0) are apparently not compatible:

```
Dec 23 10:08:38 AM  [2022-12-23 10:08:38] production.ERROR: Call to undefined function Laravel\Octane\Swoole\swoole_cpu_num() {"exception":"[object] (Error(code: 0): Call to undefined function Laravel\\Octane\\Swoole\\swoole_cpu_num() at /app/vendor/laravel/octane/src/Swoole/SwooleExtension.php:56)
Dec 23 10:08:38 AM  [stacktrace]
Dec 23 10:08:38 AM  #0 /app/vendor/laravel/octane/src/Commands/StartSwooleCommand.php(152): Laravel\\Octane\\Swoole\\SwooleExtension->cpuCount()
Dec 23 10:08:38 AM  #1 /app/vendor/laravel/octane/src/Commands/StartSwooleCommand.php(109): Laravel\\Octane\\Commands\\StartSwooleCommand->workerCount(Object(Laravel\\Octane\\Swoole\\SwooleExtension))
Dec 23 10:08:38 AM  #2 /app/vendor/laravel/octane/src/Commands/StartSwooleCommand.php(76): Laravel\\Octane\\Commands\\StartSwooleCommand->writeServerStateFile(Object(Laravel\\Octane\\Swoole\\ServerStateFile), Object(Laravel\\Octane\\Swoole\\SwooleExtension))
Dec 23 10:08:38 AM  #3 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Octane\\Commands\\StartSwooleCommand->handle(Object(Laravel\\Octane\\Swoole\\ServerProcessInspector), Object(Laravel\\Octane\\Swoole\\ServerStateFile), Object(Laravel\\Octane\\Swoole\\SwooleExtension))
Dec 23 10:08:38 AM  #4 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
Dec 23 10:08:38 AM  #5 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
Dec 23 10:08:38 AM  #6 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
Dec 23 10:08:38 AM  #7 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
Dec 23 10:08:38 AM  #8 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call(Array)
Dec 23 10:08:38 AM  #9 /app/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
Dec 23 10:08:38 AM  #10 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(151): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
Dec 23 10:08:38 AM  #11 /app/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(67): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArrayInput), Object(Illuminate\\Console\\OutputStyle))
Dec 23 10:08:38 AM  #12 /app/vendor/laravel/framework/src/Illuminate/Console/Concerns/CallsCommands.php(28): Illuminate\\Console\\Command->runCommand('octane:swoole', Array, Object(Illuminate\\Console\\OutputStyle))
Dec 23 10:08:38 AM  #13 /app/vendor/laravel/octane/src/Commands/StartCommand.php(59): Illuminate\\Console\\Command->call('octane:swoole', Array)
Dec 23 10:08:38 AM  #14 /app/vendor/laravel/octane/src/Commands/StartCommand.php(46): Laravel\\Octane\\Commands\\StartCommand->startSwooleServer()
Dec 23 10:08:38 AM  #15 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Octane\\Commands\\StartCommand->handle()
Dec 23 10:08:38 AM  #16 /app/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
Dec 23 10:08:38 AM  #17 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
Dec 23 10:08:38 AM  #18 /app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
Dec 23 10:08:38 AM  #19 /app/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
Dec 23 10:08:38 AM  #20 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(182): Illuminate\\Container\\Container->call(Array)
Dec 23 10:08:38 AM  #21 /app/vendor/symfony/console/Command/Command.php(312): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
Dec 23 10:08:38 AM  #22 /app/vendor/laravel/framework/src/Illuminate/Console/Command.php(151): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
Dec 23 10:08:38 AM  #23 /app/vendor/symfony/console/Application.php(1022): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
Dec 23 10:08:38 AM  #24 /app/vendor/symfony/console/Application.php(314): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Octane\\Commands\\StartCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
Dec 23 10:08:38 AM  #25 /app/vendor/symfony/console/Application.php(168): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
Dec 23 10:08:38 AM  #26 /app/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
Dec 23 10:08:38 AM  #27 /app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(155): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
Dec 23 10:08:38 AM  #28 /app/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
Dec 23 10:08:38 AM  #29 {main}
Dec 23 10:08:38 AM  "}
Dec 23 10:08:38 AM  
Dec 23 10:08:38 AM  In SwooleExtension.php line 56:
Dec 23 10:08:38 AM  
Dec 23 10:08:38 AM    Call to undefined function Laravel\Octane\Swoole\swoole_cpu_num()
Dec 23 10:08:38 AM  
Dec 23 10:08:38 AM  
```

As a temporary workaround you can install OpenSwoole with a fixed version using PECL:

```Dockerfile
# Example from my Dockerfile
RUN pecl install -D 'enable-openssl="yes" enable-http2="yes" enable-swoole-curl="yes" enable-mysqlnd="yes" with-postgres="yes" enable-cares="yes"' openswoole-4.12.1; docker-php-ext-enable openswoole
```

**Comment by driesvints** [comment]
We'd appreciate a PR that makes this compatible.

**Comment by nunomaduro** [comment]
Fixed on the latest version of Octane. https://github.com/laravel/octane/pull/626
