### ISSUE TITLE
Errors reported when using RoadRunner

### ISSUE THREAD

**Issue by michael-rubel** [laravel/octane#713]
### Octane Version

2.0.1

### Laravel Version

10.14.1

### PHP Version

8.2.3

### What server type are you using?

Roadrunner

### Server Version

v2023.1.5

### Description

```
local.ERROR: Unable to read frame header: Incorrect header size {"exception":"[object] (Spiral\\Goridge\\Exception\\HeaderException(code: 0): Unable to read frame header: Incorrect header size at /var/www/laravel/vendor/spiral/goridge/src/StreamRelay.php:78)
[stacktrace]
#0 /var/www/laravel/vendor/spiral/roadrunner-worker/src/Worker.php(83): Spiral\\Goridge\\StreamRelay->waitFrame()
#1 /var/www/laravel/vendor/spiral/roadrunner-http/src/HttpWorker.php(69): Spiral\\RoadRunner\\Worker->waitPayload()
#2 /var/www/laravel/vendor/spiral/roadrunner-http/src/PSR7Worker.php(102): Spiral\\RoadRunner\\Http\\HttpWorker->waitRequest()
#3 /var/www/laravel/vendor/laravel/octane/bin/roadrunner-worker(39): Spiral\\RoadRunner\\Http\\PSR7Worker->waitRequest()
#4 /var/www/laravel/vendor/bin/roadrunner-worker(120): include('...')
#5 {main}
```

```
local.ERROR: Uncaught ErrorException: file_put_contents(): Write of 811876 bytes failed with errno=32 Broken pipe in /var/www/laravel/vendor/spiral/roadrunner-worker/src/Internal/StdoutHandler.php:83
Stack trace:
#0 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#2 /var/www/laravel/vendor/spiral/roadrunner-worker/src/Internal/StdoutHandler.php(83): file_put_contents()
#3 /var/www/laravel/vendor/symfony/http-foundation/Response.php(364): Spiral\RoadRunner\Internal\StdoutHandler::Spiral\RoadRunner\Internal\{closure}()
#4 /var/www/laravel/vendor/symfony/http-foundation/Response.php(377): Symfony\Component\HttpFoundation\Response->sendContent()
#5 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(217): Symfony\Component\HttpFoundation\Response->send()
#6 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(194): Illuminate\Foundation\Bootstrap\HandleExceptions->renderHttpResponse()
#7 /var/www/laravel/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException()
#8 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#9 {main}
```

### Steps To Reproduce

Install fresh Laravel & Octane with Roadrunner as described in https://github.com/roadrunner-php/worker/issues/27

Member of `roadrunner` states that this is probably the issue with Octane in https://github.com/roadrunner-php/worker/issues/27

**Comment by mariandomanik** [comment]
We are receiving the same exceptions after updating Octane to v1.4.3 and Roadrunner

spiral/roadrunner | v2.12.3
spiral/roadrunner-cli | v2.4.0
spiral/roadrunner-http | v2.2.0
spiral/roadrunner-worker | v2.3.0

these exceptions are generated massively during deploy, when the current workers are being shut down.

**Comment by driesvints** [comment]
Thanks all. Most likely we won't get to this before Laracon so please bear with us until after the event/week.

**Comment by driesvints** [comment]
We merged a Pr for this thanks
