### ISSUE TITLE
Using Octane::concurrently() results in exception "Attempt to read property \"result\" on int"

### ISSUE THREAD

**Issue by i386** [laravel/octane#715]
### Octane Version

2.0.1

### Laravel Version

10.14.1

### PHP Version

8.2.7

### What server type are you using?

Open Swoole

### Server Version

22.0.0

### Database Driver & Version

NA

### Description

Using Octane::concurrently() results in exception "Attempt to read property \"result\" on int"

```
[$originalPath, $thumbnailPath] = Octane::concurrently([
                    function () use ($gift, $originalBasePath, $originalMime, $fsName) {
                        return Storage::disk($fsName)
                            ->putFile(GiftMedia::GALLERY_RELATIVE_PATH . '/' . $gift->uid . '/originals', new File($originalBasePath), [
                                'mimetype' => $originalMime,
                            ]);
                    },
                    function () use ($gift, $thumbBasePath, $thumbMime, $fsName) {
                         return Storage::disk($fsName)
                            ->putFile(GiftMedia::GALLERY_RELATIVE_PATH . '/' . $gift->uid . '/thumbnails', new File($thumbBasePath),
                                [
                                    'mimetype' => $thumbMime,
                                ]
                            );
                    }
                ]);
```

```
[2023-07-07 01:08:19] local.ERROR: Attempt to read property "result" on int {"error":"[object] (ErrorException(code: 0): Attempt to read property \"result\" on int at /var/www/html/vendor/laravel/octane/src/Swoole/SwooleTaskDispatcher.php:48)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/vendor/laravel/octane/src/Swoole/SwooleTaskDispatcher.php(48): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /var/www/html/vendor/laravel/octane/src/Concerns/ProvidesConcurrencySupport.php(26): Laravel\\Octane\\Swoole\\SwooleTaskDispatcher->resolve()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Laravel\\Octane\\Octane->concurrently()
#4 /var/www/html/app/Services/Producer/GiftService.php(574): Illuminate\\Support\\Facades\\Facade::__callStatic()
#5 /var/www/html/app/Services/Producer/GiftService.php(508): App\\Services\\Producer\\GiftService->saveMedia()
#6 /var/www/html/app/Http/Controllers/Producer/GiftController.php(154): App\\Services\\Producer\\GiftService->uploadGiftMedia()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\Producer\\GiftController->uploadMedia()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#9 /var/www/html/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php(21): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#10 /var/www/html/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingRoutingDispatcher.php(31): Sentry\\Laravel\\Tracing\\Routing\\TracingControllerDispatcherTracing->Sentry\\Laravel\\Tracing\\Routing\\{closure}()
#11 /var/www/html/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Routing/TracingControllerDispatcherTracing.php(20): Sentry\\Laravel\\Tracing\\Routing\\TracingRoutingDispatcher->wrapRouteDispatch()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Sentry\\Laravel\\Tracing\\Routing\\TracingControllerDispatcherTracing->dispatch()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\Route->runController()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#16 /var/www/html/app/Http/Middleware/Authorize.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Authorize->handle()
#18 /var/www/html/app/Http/Middleware/Authorize.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Authorize->handle()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(57): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Auth\\Middleware\\Authenticate->handle()
#22 /var/www/html/app/Http/Middleware/RecordLastSessionDate.php(42): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\RecordLastSessionDate->handle()
#24 /var/www/html/app/Http/Middleware/SubstituteBindings.php(55): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\SubstituteBindings->handle()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#33 /var/www/html/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestIpMiddleware.php(45): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Sentry\\Laravel\\Http\\SetRequestIpMiddleware->handle()
#35 /var/www/html/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Http/SetRequestMiddleware.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Sentry\\Laravel\\Http\\SetRequestMiddleware->handle()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#40 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#43 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#45 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#46 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#47 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#49 /var/www/html/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#50 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#51 /var/www/html/vendor/sentry/sentry-laravel/src/Sentry/Laravel/Tracing/Middleware.php(77): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Sentry\\Laravel\\Tracing\\Middleware->handle()
#53 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then()
#55 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#56 /var/www/html/vendor/laravel/octane/src/ApplicationGateway.php(34): Illuminate\\Foundation\\Http\\Kernel->handle()
#57 /var/www/html/vendor/laravel/octane/src/Worker.php(87): Laravel\\Octane\\ApplicationGateway->handle()
#58 /var/www/html/vendor/laravel/octane/bin/swoole-server(120): Laravel\\Octane\\Worker->handle()
#59 [internal function]: {closure}()
#60 /var/www/html/vendor/laravel/octane/bin/swoole-server(170): OpenSwoole\\Server->start()
#61 {main}
"} 
```

### Steps To Reproduce

[$originalPath, $thumbnailPath] = Octane::concurrently([
                    function () use ($gift, $originalBasePath, $originalMime, $fsName) {
                        return Storage::disk($fsName)
                            ->putFile(GiftMedia::GALLERY_RELATIVE_PATH . '/' . $gift->uid . '/originals', new File($originalBasePath), [
                                'mimetype' => $originalMime,
                            ]);
                    },
                    function () use ($gift, $thumbBasePath, $thumbMime, $fsName) {
                         return Storage::disk($fsName)
                            ->putFile(GiftMedia::GALLERY_RELATIVE_PATH . '/' . $gift->uid . '/thumbnails', new File($thumbBasePath),
                                [
                                    'mimetype' => $thumbMime,
                                ]
                            );
                    }
                ]);
```

**Comment by driesvints** [comment]
Hey there,

Can you first please try one of the support channels below? If you can actually identify this as a bug, feel free to open up a new issue with a link to the original one and we'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://web.libera.chat/?nick=laravelnewbie&channels=#laravel)

Thanks!

**Comment by i386** [comment]
@driesvints its definitely a bug. From my testing today, it seems to work fine on the first request but fails with this error on subsequent requests. I suspect some state between worker requests isn't getting reset or setup when a worker is used?

**Comment by driesvints** [comment]
Please try a support channel first, thanks.

**Comment by i386** [comment]
Sure. Posted https://laracasts.com/discuss/channels/laravel/using-octaneconcurrently-results-in-exception-attempt-to-read-property-result-on-int

**Comment by jaymoh** [comment]
I'm encountering the same problem - the same error. Actually, my code was working previously, but then it just stopped.

Was this one solved?

**Comment by avlima** [comment]
> I'm encountering the same problem - the same error. Actually, my code was working previously, but then it just stopped.
> 
> Was this one solved?

+1

**Comment by nikrovir** [comment]
+1
