### ISSUE TITLE
Passing a Model to a task worker eventually blocks it

### ISSUE THREAD

**Issue by borys-p** [laravel/octane#730]
### Octane Version

2.0.2

### Laravel Version

10.15.0

### PHP Version

8.2.7

### What server type are you using?

Swoole

### Server Version

5.0.3

### Description

It's a bit unusual behavior, but it is reproductible. When you pass an instance of a Model to a task worker it will eventually cause the worker to get into some kind of "blocked" state, effectively rendering it useless. What's even more interesting, it works fine at first, until the app runs out of "untainted" task workers. I was able to reproduce it on OpenSwoole and now on Swoole, as I have switched back to the original implementation. This is also the same issue as reported in #717 but with more details below.

Let's start with an example how to reproduce it. You should have a row with ID=1 in your `users` table first. Now, do the following:

```
$router->get('/test', function() {
	$user = \App\Models\User::find(1);

	return Octane::concurrently([
		fn() => $user->id
	]);
});
```

Then visit that URL and hit F5 a few times. At some point you should see the already familiar error message: `"Attempt to read property \"result\" on int"`. And that's a separate issue and I'll open another bug ticket, but the really interesting part happens in the console. Here's the full error output from the task worker:

```
PHP Fatal error:  Uncaught ReflectionException: Class "config" does not exist in /application/vendor/laravel/framework/src/Illuminate/Container/Container.php:912
Stack trace:
#0 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(912): ReflectionClass->__construct('config')
#1 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build('config')
#2 /application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(933): Illuminate\Container\Container->resolve('config', Array, true)
#3 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve('config', Array)
#4 /application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(918): Illuminate\Container\Container->make('config', Array)
#5 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(1454): Illuminate\Foundation\Application->make('config')
#6 /application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(362): Illuminate\Container\Container->offsetGet('config')
#7 /application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(122): Illuminate\Database\DatabaseManager->getDefaultConnection()
#8 /application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(92): Illuminate\Database\DatabaseManager->parseConnectionName(NULL)
#9 /application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(469): Illuminate\Database\DatabaseManager->connection()
#10 /application/app/Database/Redshift/Database.php(32): Illuminate\Database\DatabaseManager->__call('getEventDispatc...', Array)
#11 /application/vendor/laravel/framework/src/Illuminate/Database/Connection.php(744): App\Database\Redshift\Database->App\Database\Redshift\{closure}('select * from `...', Array, Object(App\Database\Redshift\Connection))
#12 /application/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#13 /application/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2747): Illuminate\Database\Connection->select('select * from `...', Array, false)
#14 /application/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2736): Illuminate\Database\Query\Builder->runSelect()
#15 /application/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3290): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#16 /application/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2735): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#17 /application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(720): Illuminate\Database\Query\Builder->get(Array)
#18 /application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(704): Illuminate\Database\Eloquent\Builder->getModels(Array)
#19 /application/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(296): Illuminate\Database\Eloquent\Builder->get(Array)
#20 /application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(598): Illuminate\Database\Eloquent\Builder->first(Array)
#21 /application/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(108): Illuminate\Database\Eloquent\Builder->firstOrFail()
#22 /application/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(61): Illuminate\Queue\QueueServiceProvider->restoreModel(Object(Illuminate\Contracts\Database\ModelIdentifier))
#23 /application/vendor/laravel/framework/src/Illuminate/Queue/QueueServiceProvider.php(61): Illuminate\Queue\QueueServiceProvider->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#24 [internal function]: Illuminate\Queue\QueueServiceProvider->Illuminate\Queue\{closure}(Array)
#25 /application/vendor/laravel/serializable-closure/src/Serializers/Native.php(179): call_user_func(Object(Closure), Array)
#26 [internal function]: Laravel\SerializableClosure\Serializers\Native->__unserialize(NULL)
#27 /application/vendor/laravel/serializable-closure/src/Serializers/Signed.php(87): unserialize('O:46:"Laravel\\S...')
#28 [internal function]: Laravel\SerializableClosure\Serializers\Signed->__unserialize(Array)
#29 /application/vendor/laravel/octane/bin/swoole-server(170): Swoole\Server->start()
#30 {main}
Next Illuminate\Contracts\Container\BindingResolutionException: Target class [config] does not exist. in /application/vendor/laravel/framework/src/Illuminate/Container/Container.php:914
#0 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\Container\Container->build('config')
#1 /application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(933): Illuminate\Container\Container->resolve('config', Array, true)
#2 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\Foundation\Application->resolve('config', Array)
#3 /application/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(918): Illuminate\Container\Container->make('config', Array)
#4 /application/vendor/laravel/framework/src/Illuminate/Container/Container.php(1454): Illuminate\Foundation\Application->make('config')
#5 /application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(362): Illuminate\Container\Container->offsetGet('config')
#6 /application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(122): Illuminate\Database\DatabaseManager->getDefaultConnection()
#7 /application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(92): Illuminate\Database\DatabaseManager->parseConnectionName(NULL)
#8 /application/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(469): Illuminate\Database\DatabaseManager->connection()
#9 /application/app/Database/Redshift/Database.php(32): Illuminate\Database\DatabaseManager->__call('getEventDispatc...', Array)
#10 /application/vendor/laravel/framework/src/Illuminate/Database/Connection.php(744): App\Database\Redshift\Database->App\Database\Redshift\{closure}('select * from `...', Array, Object(App\Database\Redshift\Connection))
#11 /application/vendor/laravel/framework/src/Illuminate/Database/Connection.php(407): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#12 /application/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2747): Illuminate\Database\Connection->select('select * from `...', Array, false)
#13 /application/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2736): Illuminate\Database\Query\Builder->runSelect()
#14 /application/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3290): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#15 /application/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2735): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#16 /application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(720): Illuminate\Database\Query\Builder->get(Array)
#17 /application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(704): Illuminate\Database\Eloquent\Builder->getModels(Array)
#18 /application/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(296): Illuminate\Database\Eloquent\Builder->get(Array)
#19 /application/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(598): Illuminate\Database\Eloquent\Builder->first(Array)
#20 /application/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(108): Illuminate\Database\Eloquent\Builder->firstOrFail()
#21 /application/vendor/laravel/framework/src/Illuminate/Queue/SerializesAndRestoresModelIdentifiers.php(61): Illuminate\Queue\QueueServiceProvider->restoreModel(Object(Illuminate\Contracts\Database\ModelIdentifier))
#22 /application/vendor/laravel/framework/src/Illuminate/Queue/QueueServiceProvider.php(61): Illuminate\Queue\QueueServiceProvider->getRestoredPropertyValue(Object(Illuminate\Contracts\Database\ModelIdentifier))
#23 [internal function]: Illuminate\Queue\QueueServiceProvider->Illuminate\Queue\{closure}(Array)
#24 /application/vendor/laravel/serializable-closure/src/Serializers/Native.php(179): call_user_func(Object(Closure), Array)
#25 [internal function]: Laravel\SerializableClosure\Serializers\Native->__unserialize(NULL)
#26 /application/vendor/laravel/serializable-closure/src/Serializers/Signed.php(87): unserialize('O:46:"Laravel\\S...')
#27 [internal function]: Laravel\SerializableClosure\Serializers\Signed->__unserialize(Array)
#28 /application/vendor/laravel/octane/bin/swoole-server(170): Swoole\Server->start()
#29 {main}
  thrown in /application/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 914
PHP Stack trace:
PHP   1. {main}() /application/vendor/laravel/octane/bin/swoole-server:0
PHP   2. Swoole\Server->start() /application/vendor/laravel/octane/bin/swoole-server:170
  503    GET /test ......................................... 24.66 mb 811.63 ms
```

At this point the task workers will be constantly throwing that exception until you restart the PHP processes. 

As you can see, it is somehow caused by the attempt to restore the model from the database while unserializing the closure to which the model is bound. I haven't investigated it much further, as there's lots of auto-wiring reflection magic going on and tis' a scary place.

By the way, it's a bit silly what Laravel does here when blindly attempting to re-load the Model instead of serializing/unserializing its inner state. In the example above you can just replace the `User::find()` with instantiating a new Model, hydrate it with `['id' => 1]` and the framework will do the same. 

### Steps To Reproduce

As above in the description.

**Comment by borys-p** [comment]
As a follow-up, on my local environment I have Swoole built with tracing and debugging enabled, so I tried looking in those logs. Interestingly, enabling tracing makes the issue harder to reproduce, but it eventually happens.

Here are the Swoole logs when it works:

```
[2023-08-08 17:10:02 #189.5]	TRACE	Socket::recv(:730): recv 367/65536 bytes, errno=11
[2023-08-08 17:10:02 #189.5]	TRACE	Port_onRead_http(:507): content-length=0, keep-alive=1, chunked=0
[2023-08-08 17:10:02 #189.5]	TRACE	Server::dispatch_task(:884): dispatch task, size=367 bytes
[2023-08-08 17:10:02 #189.5]	TRACE	Server::dispatch_task(:892): session_id=3, len=367, qb=367
[2023-08-08 17:10:02 *266.5]	TRACE	Server::worker_accept_event(:133): [Worker] session_id=3, len=367, qb=0
[2023-08-08 17:10:02 *266.5]	TRACE	php_swoole_http_server_onReceive(:83): http request from 3 with 367 bytes: <<EOF
GET /test HTTP/1.1
Host: localhost:1337
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15
Accept-Language: pl-PL,pl;q=0.9
Accept-Encoding: gzip, deflate
Connection: keep-alive


EOF
[2023-08-08 17:10:02 *266.5]	TRACE	http_request_message_complete(:792): request body length=0
[2023-08-08 17:10:02 *266.5]	TRACE	swoole_http_server_onBeforeRequest(:343): serv->gs->concurrency=1, max_concurrency=4294967295
[2023-08-08 17:10:02 *266.5]	TRACE	swoole_http_server_onAfterResponse(:361): serv->gs->concurrency=0, max_concurrency=4294967295
[2023-08-08 17:10:02 *266.5]	TRACE	ProcessFactory::finish(:190): worker_id=5, type=2
[2023-08-08 17:10:02 #189.5]	TRACE	Socket::send(:756): send 291/291 bytes, errno=22
```

and when it fails for the first time:

```
[2023-08-08 17:10:12 #189.7]	TRACE	ReactorEpoll::add(:107): add events[fd=167#7, type=0, events=512]
[2023-08-08 17:10:12 #189.10]	TRACE	Timer::select(:196): timer msec=66493, round=136
[2023-08-08 17:10:12 #189.7]	TRACE	Socket::recv(:730): recv 367/65536 bytes, errno=11
[2023-08-08 17:10:12 #189.7]	TRACE	Port_onRead_http(:507): content-length=0, keep-alive=1, chunked=0
[2023-08-08 17:10:12 #189.7]	TRACE	Server::dispatch_task(:884): dispatch task, size=367 bytes
[2023-08-08 17:10:12 #189.7]	TRACE	Server::dispatch_task(:892): session_id=5, len=367, qb=367
[2023-08-08 17:10:12 *268.7]	TRACE	Server::worker_accept_event(:133): [Worker] session_id=5, len=367, qb=0
[2023-08-08 17:10:12 *268.7]	TRACE	php_swoole_http_server_onReceive(:83): http request from 5 with 367 bytes: <<EOF
GET /test HTTP/1.1
Host: localhost:1337
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15
Accept-Language: pl-PL,pl;q=0.9
Accept-Encoding: gzip, deflate
Connection: keep-alive


EOF
[2023-08-08 17:10:12 *268.7]	TRACE	http_request_message_complete(:792): request body length=0
[2023-08-08 17:10:12 *268.7]	TRACE	swoole_http_server_onBeforeRequest(:343): serv->gs->concurrency=3, max_concurrency=4294967295
[2023-08-08 17:10:12 *266.5]	TRACE	swoole_http_server_onAfterResponse(:361): serv->gs->concurrency=2, max_concurrency=4294967295
[2023-08-08 17:10:12 *266.5]	TRACE	ProcessFactory::finish() (ERRNO 1004): send 1603 bytes failed, because session#3 is closed
[2023-08-08 17:10:12 *266.5]	TRACE	ProcessFactory::end(:217): session_id=3, fd=165
[2023-08-08 17:10:12 *266.5]	TRACE	ProcessFactory::finish(:190): worker_id=5, type=4
[2023-08-08 17:10:12 #189.5]	TRACE	Server::close_connection(:195): Close Event.fd=165|from=5
[2023-08-08 17:10:12 #189.5]	TRACE	Reactor::_close(:205): fd=165
[2023-08-08 17:10:12 *266.5]	TRACE	ProcessFactory::end() (ERRNO 1005): session#3 does not exists
[2023-08-08 17:10:12 *267.6]	TRACE	swoole_http_server_onAfterResponse(:361): serv->gs->concurrency=1, max_concurrency=4294967295
[2023-08-08 17:10:12 *267.6]	TRACE	ProcessFactory::finish() (ERRNO 1004): send 1603 bytes failed, because session#4 is closed
[2023-08-08 17:10:12 *267.6]	TRACE	ProcessFactory::end(:217): session_id=4, fd=166
[2023-08-08 17:10:12 *267.6]	TRACE	ProcessFactory::finish(:190): worker_id=6, type=4
[2023-08-08 17:10:12 #189.6]	TRACE	Server::close_connection(:195): Close Event.fd=166|from=6
[2023-08-08 17:10:12 #189.6]	TRACE	Reactor::_close(:205): fd=166
[2023-08-08 17:10:12 *267.6]	TRACE	ProcessFactory::end(:217): session_id=4, fd=166
[2023-08-08 17:10:13 #189.10]	TRACE	Timer::select(:196): timer msec=67000, round=137
[2023-08-08 17:10:13 #189.10]	TRACE	Timer::select(:206): id=1, exec_msec=67000, round=0, exist=1
[2023-08-08 17:10:13 #189.10]	TRACE	Timer::select(:196): timer msec=67239, round=138
[2023-08-08 17:10:13 #189.10]	TRACE	Timer::select(:206): id=2, exec_msec=67237, round=0, exist=1
[2023-08-08 17:10:13 *268.7]	TRACE	swoole_http_server_onAfterResponse(:361): serv->gs->concurrency=0, max_concurrency=4294967295
[2023-08-08 17:10:13 *268.7]	TRACE	ProcessFactory::finish(:190): worker_id=7, type=2
[2023-08-08 17:10:13 #189.7]	TRACE	Socket::send(:756): send 1603/1603 bytes, errno=22
```

and some time after that, after the worker gets "tainted":

```
[2023-08-08 17:14:55 #189.10]	TRACE	Server::accept_connection(:169): [Master] Accept new connection. maxfd=154|minfd=154|reactor_id=10|conn=165
[2023-08-08 17:14:55 #189.10]	TRACE	Socket::send(:756): send 40/40 bytes, errno=22
[2023-08-08 17:14:55 #189.5]	TRACE	ReactorEpoll::add(:107): add events[fd=165#5, type=0, events=512]
[2023-08-08 17:14:55 #189.10]	TRACE	Timer::select(:196): timer msec=349788, round=703
[2023-08-08 17:14:55 #189.5]	TRACE	Socket::recv(:730): recv 367/65536 bytes, errno=11
[2023-08-08 17:14:55 #189.5]	TRACE	Port_onRead_http(:507): content-length=0, keep-alive=1, chunked=0
[2023-08-08 17:14:55 #189.5]	TRACE	Server::dispatch_task(:884): dispatch task, size=367 bytes
[2023-08-08 17:14:55 #189.5]	TRACE	Server::dispatch_task(:892): session_id=6, len=367, qb=367
[2023-08-08 17:14:55 *266.5]	TRACE	Server::worker_accept_event(:133): [Worker] session_id=6, len=367, qb=0
[2023-08-08 17:14:55 *266.5]	TRACE	php_swoole_http_server_onReceive(:83): http request from 6 with 367 bytes: <<EOF
GET /test HTTP/1.1
Host: localhost:1337
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15
Accept-Language: pl-PL,pl;q=0.9
Accept-Encoding: gzip, deflate
Connection: keep-alive


EOF
[2023-08-08 17:14:55 *266.5]	TRACE	http_request_message_complete(:792): request body length=0
[2023-08-08 17:14:55 *266.5]	TRACE	swoole_http_server_onBeforeRequest(:343): serv->gs->concurrency=1, max_concurrency=4294967295
[2023-08-08 17:14:56 #189.10]	TRACE	Timer::select(:196): timer msec=350000, round=704
[2023-08-08 17:14:56 #189.10]	TRACE	Timer::select(:206): id=1, exec_msec=350000, round=0, exist=1
[2023-08-08 17:14:56 #189.10]	TRACE	Timer::select(:196): timer msec=350238, round=705
[2023-08-08 17:14:56 #189.10]	TRACE	Timer::select(:206): id=2, exec_msec=350237, round=0, exist=1
[2023-08-08 17:14:56 *266.5]	TRACE	swoole_http_server_onAfterResponse(:361): serv->gs->concurrency=0, max_concurrency=4294967295
[2023-08-08 17:14:56 *266.5]	TRACE	ProcessFactory::finish(:190): worker_id=5, type=2
[2023-08-08 17:14:56 #189.5]	TRACE	Socket::send(:756): send 1603/1603 bytes, errno=22
```

**Comment by nunomaduro** [comment]
The code bellow, the `$user` variable is an instance of the query builder, and not an user model:
```
$user = User::find(1);
```

You should use `User::first()` instead. However, I do think the feedback regarding the error can be improved, so lets follow up at https://github.com/laravel/octane/issues/731.

**Comment by borys-p** [comment]
Nope, `find()` will be forwarded to the Eloquent Builder, which does the following:

```
    public function find($id, $columns = ['*'])
    {
        if (is_array($id) || $id instanceof Arrayable) {
            return $this->findMany($id, $columns);
        }

        return $this->whereKey($id)->first($columns);
    }
```

So it's a full-fledged Model at this point.

This also doesn't change the fact that the task worker enters some type of broken state, and #731 seems to be only a symptom of a much deeper issue. Please take a look at the attached stack trace and how even the `config` can't be resolved from the Container, just like there was nothing bound to the sandbox.

**Comment by pslxx** [comment]
This is an existential problem that I have encountered, and failure to attempt to pass serialized models often results in a deserialization failure and then the process terminates

**Comment by avlima** [comment]
Did you find any solution? I still have this problem :/

**Comment by ingria** [comment]
still having this problem in v2.3.3

**Comment by andreaszak** [comment]
still having this issue in v2.8.2

**Comment by iskander-g** [comment]
Still having this issue in 2.9.1

**Comment by binaryfire** [comment]
Just hit this issue as well
