### ISSUE TITLE
Fatal errors during closure unserialization are not catched properly

### ISSUE THREAD

**Issue by borys-p** [laravel/octane#731]
### Octane Version

2.0.2

### Laravel Version

10.15.0

### PHP Version

8.2.7

### What server type are you using?

Swoole

### Server Version

5.0.3

### Description

This is a follow-up to #730 (and #717), but happening on the other side.

Octane does a pretty good job when catching any kind of errors happening in the task workers, including fatal errors. Then `TaskExceptionResult` is reported back to `SwooleTaskDispatcher::resolve()` and everything works as expected.

However, it seems that if the fatal error happens when the closure is unserialized, it won't be catched and the task worker will simply return 0 (zero) as the result, leading to the error that we already know: `"Attempt to read property \"result\" on int"` with the following stack trace:

```
#0 /application/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Attempt to read...', '/application/ve...', 53)
#1 /application/vendor/laravel/octane/src/Swoole/SwooleTaskDispatcher.php(53): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Attempt to read...', '/application/ve...', 53)
#2 /application/vendor/laravel/octane/src/Concerns/ProvidesConcurrencySupport.php(26): Laravel\\Octane\\Swoole\\SwooleTaskDispatcher->resolve(Array, 3000)
#3 /application/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(353): Laravel\\Octane\\Octane->concurrently(Array)
#4 /application/routes/web.php(11): Illuminate\\Support\\Facades\\Facade::__callStatic('concurrently', Array)
#5 /application/vendor/laravel/framework/src/Illuminate/Routing/CallableDispatcher.php(40): Illuminate\\Routing\\RouteFileRegistrar->{closure}()
#6 /application/vendor/laravel/framework/src/Illuminate/Routing/Route.php(237): Illuminate\\Routing\\CallableDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Closure))
#7 /application/vendor/laravel/framework/src/Illuminate/Routing/Route.php(208): Illuminate\\Routing\\Route->runCallable()
#8 /application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(799): Illuminate\\Routing\\Route->run()
#9 /application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#10 /application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#11 /application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(798): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#12 /application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(777): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#13 /application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(741): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#14 /application/vendor/laravel/framework/src/Illuminate/Routing/Router.php(730): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#15 /application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#16 /application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#17 /application/app/Http/Middleware/TenantDatabaseRouter.php(100): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\TenantDatabaseRouter->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#19 /application/app/Http/Middleware/Instrumentation.php(36): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#20 /application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\Instrumentation->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#21 /application/app/Http/Middleware/SetTenantInfo.php(20): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#22 /application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\SetTenantInfo->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#25 /application/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#26 /application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#27 /application/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#28 /application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#29 /application/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#30 /application/vendor/laravel/octane/src/ApplicationGateway.php(34): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#31 /application/vendor/laravel/octane/src/Worker.php(86): Laravel\\Octane\\ApplicationGateway->handle(Object(Illuminate\\Http\\Request))
#32 /application/vendor/laravel/octane/bin/swoole-server(120): Laravel\\Octane\\Worker->handle(Object(Illuminate\\Http\\Request), Object(Laravel\\Octane\\RequestContext))
#33 [internal function]: {closure}(Object(Swoole\\Http\\Request), Object(Swoole\\Http\\Response))
#34 /application/vendor/laravel/octane/bin/swoole-server(170): Swoole\\Server->start()
#35 {main}
```

So far, I have at least two ways to reproduce it. One is the Model-related issue reported in #730, but that's a bit annoying to work with. The other one is as follows:

```
readonly class A {
	public function __construct(
		public array $a = [],
	) {}
}

$router->get('/', function() {
	$a = new A();

	return Octane::concurrently([
		fn() => $a->a
	]);
});
```

**Note: I'm fully aware that `serializable-closure` does not support readonly properties.** And that it is written right in the README. It's just a way to trigger a fatal error early enough to observe the behavior described earlier. It is probably also doable with a manually crafted payload that will cause an OOM error, but I haven't tried that yet.

If those errors can't be catched, then the resolving code should at least be aware of that scalar value being returned.

### Steps To Reproduce

As above in the description.

**Comment by nunomaduro** [comment]
No problem - make a pull request - and we will work from there. Thank you!
